export default Object.freeze({
    OPEN: "OPEN", 
    CREATE_BOARD: "CREATE_BOARD",
    SHOW_MOVES: "SHOW_MOVES",
    MOVE_PIECE: "MOVE_PIECE",
    PROMOTED_PIECE: "PROMOTED_PIECE",
    QUIT_GAME: "QUIT_GAME"
});